name: Qodana
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches:
      - main
      - develop

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          node-version: 'lts'
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@latest
        with:
          args: --apply-fixes
          pr-mode: false
          push-fixes: pull-request
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}